// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getCategoryAnalysis = `-- name: GetCategoryAnalysis :many
SELECT
  category,
  SUM(amount) AS total
FROM records
WHERE deleted_at IS NULL
  AND ($1::UUID IS NULL OR user_id = $1::UUID)
GROUP BY category
ORDER BY total DESC
`

type GetCategoryAnalysisRow struct {
	Category string
	Total    int64
}

func (q *Queries) GetCategoryAnalysis(ctx context.Context, userID uuid.NullUUID) ([]GetCategoryAnalysisRow, error) {
	rows, err := q.db.QueryContext(ctx, getCategoryAnalysis, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoryAnalysisRow
	for rows.Next() {
		var i GetCategoryAnalysisRow
		if err := rows.Scan(&i.Category, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardSummary = `-- name: GetDashboardSummary :one
SELECT
  COALESCE(SUM(CASE WHEN type = 'income' THEN amount ELSE 0 END), 0)::TEXT AS total_income,
  COALESCE(SUM(CASE WHEN type = 'expense' THEN amount ELSE 0 END), 0)::TEXT AS total_expense
FROM records
WHERE deleted_at IS NULL
  AND ($1::UUID IS NULL OR user_id = $1::UUID)
`

type GetDashboardSummaryRow struct {
	TotalIncome  string
	TotalExpense string
}

func (q *Queries) GetDashboardSummary(ctx context.Context, userID uuid.NullUUID) (GetDashboardSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getDashboardSummary, userID)
	var i GetDashboardSummaryRow
	err := row.Scan(&i.TotalIncome, &i.TotalExpense)
	return i, err
}

const getRecent = `-- name: GetRecent :many
SELECT id, user_id, amount, type, category, note, date, created_at, updated_at, deleted_at, created_by
FROM records
WHERE deleted_at IS NULL
  AND ($1::UUID IS NULL OR user_id = $1::UUID)
ORDER BY date DESC
LIMIT 10
`

func (q *Queries) GetRecent(ctx context.Context, userID uuid.NullUUID) ([]Record, error) {
	rows, err := q.db.QueryContext(ctx, getRecent, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Type,
			&i.Category,
			&i.Note,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrends = `-- name: GetTrends :many
SELECT
  TO_CHAR(date, 'YYYY-MM') AS month,
  SUM(CASE WHEN type = 'income' THEN amount ELSE 0 END) AS income,
  SUM(CASE WHEN type = 'expense' THEN amount ELSE 0 END) AS expense
FROM records
WHERE deleted_at IS NULL
  AND ($1::UUID IS NULL OR user_id = $1::UUID)
GROUP BY month
ORDER BY month DESC
`

type GetTrendsRow struct {
	Month   string
	Income  int64
	Expense int64
}

func (q *Queries) GetTrends(ctx context.Context, userID uuid.NullUUID) ([]GetTrendsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTrends, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTrendsRow
	for rows.Next() {
		var i GetTrendsRow
		if err := rows.Scan(&i.Month, &i.Income, &i.Expense); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
