// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Record struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Amount    string
	Type      string
	Category  string
	Note      sql.NullString
	Date      time.Time
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}
