// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: records.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createRecord = `-- name: CreateRecord :one
INSERT INTO records (
  id,
  user_id,
  amount,
  type,
  category,
  note,
  date
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, amount, type, category, note, date, created_at, updated_at, deleted_at
`

type CreateRecordParams struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	Amount   string
	Type     string
	Category string
	Note     sql.NullString
	Date     time.Time
}

func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) (Record, error) {
	row := q.db.QueryRowContext(ctx, createRecord,
		arg.ID,
		arg.UserID,
		arg.Amount,
		arg.Type,
		arg.Category,
		arg.Note,
		arg.Date,
	)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Type,
		&i.Category,
		&i.Note,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
